### PR TITLE
Build using GitHub actions

### PR DESCRIPTION
**Pull request by mondras**
This commit makes use of github actions to build the site on the
gituhb provided CI/CD environment.

It deletes the documentation from version control so that we can only
keep the sources there - cleaner history.

It also deletes the deploy script and moves the logic within the `npm
run build` command in `package.json`

### CODE REVIEW

**Comment by actuallymentor** [comment]
Wonderful addition!

Could you recommit excluding the `docs` folder?

**Comment by mondras** [comment]
You mean leaving the docs folder in it? Is this for merging? 

Keeping the under version control it's kind of not ideal right?

**Comment by andremalan** [comment]
Yeah, would be wonderful not having to update the docs folder and just have it happen on deploy.

**Comment by actuallymentor** [comment]
@mondras I'd love to merge your PR so I can also set the member database to update through github actions.

Could you please remove the `docs/*` from your commit?

Thank you!

**Comment by mondras** [comment]
@actuallymentor done

**Comment by mondras** [comment]
You'll have to look into the action since adding back the docs folder broke the action. It's expecting that folder not to exist. Good luck!

**Comment by actuallymentor** [comment]
Thank you, I'll get on it!

**Comment by actuallymentor** [comment]
I ended up using a different GH actions structure, but thanks for taking the initiative on this!

**Pull request merged**
